<?PHP
class DbCacheDriver implements CacheDriver
{
	protected $db = null;
	protected $table = 'cache_a';
	public function __construct($table='cache_a')
	{
		$this->table = $table;
		if(is_object($GLOBALS['db'])) $this->db=$GLOBALS['db'];
		else  throw new CacheException('Unable to use mysql database.');
	}

	/**
	 * Sets data to cache
	 *
	 * @param string $groupName Name of groupName of cache
	 * @param string $identifier Identifier of data
	 * @param mixed $data Data
	 * @return boolean
	 */
	public function set($groupName, $identifier, $data){
		$sql = "INSERT INTO `". $this->table ."` (groupName,name,content,addtime) VALUES ('$groupName','$identifier','$data',UNIX_TIMESTAMP())";
		return $this->db->query($sql)?true:false;
	}

	/**
	 * Gets data from cache
	 *
	 * @param string $groupName Name of groupName
	 * @param string $identifier Identifier of data
	 * @return mixed
	 */
	public function get($groupName, $identifier){
		$sql = "SELECT content FROM `". $this->table ."` WHERE groupName='$groupName' AND name='$identifier'";
		return $this->db->getOne($sql);
	}

	/**
	 * Check if cache data exists
	 *
	 * @param string $groupName Name of groupName
	 * @param string $identifier Identifier
	 * @return boolean
	 */
	public function exists($groupName, $identifier){
		$sql = "SELECT id FROM `". $this->table ."` WHERE groupName='$groupName' AND name='$identifier'";
		return $this->db->getOne($sql)>0?true:false;
	}

	/**
	 * Clears cache of specified identifier of groupName
	 *
	 * @param string $groupName Name of groupName
	 * @param string $identifier Identifier
	 * @return boolean
	 */
	public function clearCache($groupName, $identifier){
		$sql = "DELETE FROM `". $this->table ."` WHERE groupName='$groupName' AND name='$identifier'";
		$this->db->query($sql);
	}

	/**
	 * Clears cache of specified groupName
	 *
	 * @param string $groupName Name of groupName
	 * @return boolean
	 */
	public function cleargroupCache($groupName){
		$sql = "DELETE FROM `". $this->table ."` WHERE groupName='$groupName'";
		$this->db->query($sql);
	}

	/**
	 * Clears all cache generated by this class with this driver
	 *
	 * @return boolean
	 */
	public function clearAllCache(){
		$sql = "TRUNCATE TABLE `". $this->table ."`";
		$this->db->query($sql);
	}

	/**
	 * Gets last modification time of specified cache data
	 *
	 * @param string $groupName Name of groupName
	 * @param string $identifier Identifier
	 * @return int
	 */
	public function modificationTime($groupName, $identifier){
		$sql = "SELECT addtime FROM `". $this->table ."` WHERE groupName='$groupName' AND name='$identifier'";
		$addtime = $this->db->getOne($sql);
		return intval($addtime);
	}
} /* end of class FileCacheDriver */
?>